name: smart_school
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  dio: ^5.8.0+1
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icons8-school-100.png"